params:
  method: adversarial-pgd-training
  evaluation_dir: data/out/autoattack/resnet18_cifar10
  loss_fn: cross_entropy
  comment: AutoAttack evaluation for adversarial PGD training checkpoint

model:
  name: resnet18_10
  num_classes: 10
  pretrained: true
  weights_path: outputs/train/adversarial_pgd/cifar10_resnet18/resnet18_10_cifar10_20260507_074349/checkpoints/best.pth

test_dataset:
  name: cifar10
  root_dir: data/dataset/cifar_10
  train: false
  download: true
  batch_size: 128

normalization:
  enabled: true
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2470, 0.2435, 0.2616]

autoattack:
  norm: Linf
  epsilon: 0.031372549
  version: "custom"
  attacks_to_run:
    - "apgd-ce"
  max_examples: 1000
  seed: 0

wandb:
  enabled: false
  project: certified-robustness
  entity: ""
  run_name: ""
  tags:
    - evaluation
    - autoattack
    - cifar10
    - resnet18
    - adv-pgd
