model:
  name: resnet18_10
  weights_path: outputs/train/gaussian_noise/cifar10_resnet18/resnet18_10_cifar10_20260502_185827/checkpoints/best.pth
  pretrained: true
  num_classes: 10

test_dataset:
  name: cifar10
  root_dir: data/dataset/cifar_10
  download: true
  batch_size: 128

fgsm:
  epsilon: 0.03137
  loss_fn: cross_entropy

pgd:
  epsilon: 0.03137
  alpha: 0.00784
  steps: 10
  norm: l2
  loss_fn: cross_entropy



params:
  method: gaussian-noise
  comment: resnet18_10 cifar10 gaussian evaluation
  loss_fn: cross_entropy
  sigma: 0.25
  cert_mode: hard
  N0: 100
  N: 1000
  alpha: 0.001
  beta: 16.0
  evaluation_dir: data/out/evaluation/resnet18_cifar10


normalization:
  enabled: true
  mean: [ 0.4914, 0.4822, 0.4465 ]
  std: [ 0.2470, 0.2435, 0.2616 ]