model:
  name: resnet18_10
  weights_path: data/models/resnet/resnet_18_cifar_10/resnet18_cifar10_full.pth

datasets:
  train:
    name: cifar10
    root_dir: data/dataset/cifar_10
    download: true
    batch_size: 128

  test:
    name: cifar10
    root_dir: data/dataset/cifar_10
    download: true
    batch_size: 128

attacks:
  - name: fgsm
    epsilon: 0.03137
    loss_fn: cross_entropy

  - name: pgd
    epsilon: 0.03137
    alpha: 0.00784
    steps: 10
    norm: Linf
    loss_fn: cross_entropy
    mean: [ 0.4914, 0.4822, 0.4465 ]
    std: [ 0.2470, 0.2435, 0.2616 ]

#  - name: stadv
#    alpha: 0.01
#    steps: 100
#    tau: 0.05
#    targeted: false
#    loss_fn: cross_entropy
