model:
  name: resnet18_10
  pretrained: false

datasets:
  train:
    name: cifar10
    root_dir: data/dataset/cifar_10
    download: true
    batch_size: 128

  test:
    name: cifar10
    root_dir: data/dataset/cifar_10
    download: true
    batch_size: 128

attacks:
  - name: fgsm
    epsilon: 0.03137
    loss_fn: cross_entropy
    mean: [ 0.4914, 0.4822, 0.4465 ]
    std: [ 0.2023, 0.1994, 0.2010 ]

  - name: pgd
    epsilon: 0.03137
    alpha: 0.00784
    steps: 10
    norm: Linf
    loss_fn: cross_entropy
    mean: [ 0.4914, 0.4822, 0.4465 ]
    std: [ 0.2023, 0.1994, 0.2010 ]


training:
  enabled: true
  epochs: 100
  seed: 42
  device: auto

  optimizer:
    name: sgd
    lr: 0.1
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true

  scheduler:
    name: cosine
    eta_min: 0.0

  wandb:
    enabled: true
    project: certified-robustness
    run_name: resnet18-cifar10-baseline
    tags:
      - cifar10
      - resnet18
      - baseline

  save_dir: ./checkpoints
  save_best: true
  save_last: true
  metric_for_best_model: test_accuracy


